<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Relatório CNCS {{ $year }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #1d4ed8; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { max-width: 150px; }
        h1 { color: #1d4ed8; font-size: 24px; }
        h2 { color: #1e40af; font-size: 20px; margin-top: 30px; }
        p { text-align: justify; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background-color: #f3f4f6; color: #111; }
        .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 50px; text-align: center; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Annual Cyber Risk Assessment Report - CNCS') }}</h1>
        <p>{{ __('Issue Year') }}: {{ $year }}</p>
    </div>

    <h2>1. {{ __('Introduction') }}</h2>
    <p>
        {{ __("This report documents the risk assessment of the organization's information assets, in accordance with the guidelines of the National Cybersecurity Reference Framework (QNRCS). This document serves as proof of the continuous effort to maintain the confidentiality, integrity, and availability of the systems.") }}
    </p>

    <h2>2. {{ __('Assets Summary') }}</h2>
    <p>{{ __('Below is the list of assets assessed in the current year, as well as their residual risk level:') }}</p>

    <table>
        <thead>
            <tr>
                <th>{{ __('Asset Name') }}</th>
                <th>{{ __('Type') }}</th>
                <th>{{ __('Global Risk') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $asset)
                <tr>
                    <td>{{ $asset->name }}</td>
                    <td>{{ __($asset->type->name ?? 'None') }}</td>
                    <td>{{ $asset->highestRemainingRisk() }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Automatically generated by the Risk Management System on') }} {{ now()->format('d/m/Y H:i') }}
    </div>
</body>
</html>