<?php

return [
    'enabled' => env('GRAFANA_ENABLED', true),
    'base_url' => rtrim(env('GRAFANA_BASE_URL', 'http://localhost:3000'), '/'),
    'dashboards' => [
        'soc_overview' => [
            'uid' => env('GRAFANA_DASHBOARD_SOC_UID', 'arm-soc-overview'),
            'title' => 'SOC Overview',
            'description' => 'Cross-domain SOC summary with high-level pressure indicators plus a first-response queue for the accounts and assets that require action first.',
            'time_range' => 'now-7d',
            'panels' => [
                ['id' => 1, 'title' => 'Open Alerts', 'size' => 'stat'],
                ['id' => 2, 'title' => 'Critical Alerts', 'size' => 'stat'],
                ['id' => 3, 'title' => 'New Alerts 24h', 'size' => 'stat'],
                ['id' => 4, 'title' => 'Active External Hosts', 'size' => 'stat'],
                ['id' => 5, 'title' => 'Unlinked Hosts', 'size' => 'stat'],
                ['id' => 6, 'title' => 'KEV Findings', 'size' => 'stat'],
                ['id' => 7, 'title' => 'Threat Events Trend', 'size' => 'chart'],
                ['id' => 8, 'title' => 'Open Alerts By Severity', 'size' => 'chart'],
                ['id' => 11, 'title' => 'Problem Load: Assets vs M365 Accounts', 'size' => 'chart'],
            ],
        ],
        'm365_monitoring' => [
            'uid' => env('GRAFANA_DASHBOARD_M365_UID', 'arm-m365-monitoring'),
            'title' => 'M365 Monitoring',
            'description' => 'Most problematic accounts, risky source IPs and Microsoft Graph event trends.',
            'time_range' => 'now-7d',
            'panels' => [
                ['id' => 1, 'title' => 'Threat Events 24h', 'size' => 'stat'],
                ['id' => 2, 'title' => 'Accounts 24h', 'size' => 'stat'],
                ['id' => 3, 'title' => 'Source IPs 24h', 'size' => 'stat'],
                ['id' => 4, 'title' => 'Open M365 Alerts', 'size' => 'stat'],
                ['id' => 5, 'title' => 'All M365 Threat Events', 'size' => 'chart'],
                ['id' => 6, 'title' => 'Risk-Signaled Events', 'size' => 'chart'],
                ['id' => 7, 'title' => 'Top Source Countries', 'size' => 'chart'],
                ['id' => 8, 'title' => 'Risk Level Distribution', 'size' => 'chart'],
                ['id' => 9, 'title' => 'Accounts With Highest Pressure', 'size' => 'table'],
                ['id' => 10, 'title' => 'Source IPs Driving Risk', 'size' => 'table'],
            ],
        ],
        'attack_surface' => [
            'uid' => env('GRAFANA_DASHBOARD_ATTACK_SURFACE_UID', 'arm-attack-surface'),
            'title' => 'Attack Surface',
            'description' => 'Discovery coverage, enrichment failures and the most exposed external hosts.',
            'time_range' => 'now-30d',
            'panels' => [
                ['id' => 1, 'title' => 'Active Hosts', 'size' => 'stat'],
                ['id' => 2, 'title' => 'Filtered Hosts', 'size' => 'stat'],
                ['id' => 3, 'title' => 'Unlinked Hosts', 'size' => 'stat'],
                ['id' => 4, 'title' => 'New Hosts 7d', 'size' => 'stat'],
                ['id' => 5, 'title' => 'Host Status Breakdown', 'size' => 'chart'],
                ['id' => 6, 'title' => 'Active Findings By Type', 'size' => 'chart'],
                ['id' => 7, 'title' => 'Enrichment Runs By Provider', 'size' => 'chart'],
                ['id' => 8, 'title' => 'New Hosts Trend', 'size' => 'chart'],
                ['id' => 9, 'title' => 'Recent Enrichment Failures', 'size' => 'table'],
                ['id' => 10, 'title' => 'Priority External Hosts', 'size' => 'table'],
                ['id' => 11, 'title' => 'Recent Discovery Runs', 'size' => 'table'],
            ],
        ],
        'vulnerability_risk' => [
            'uid' => env('GRAFANA_DASHBOARD_VULNERABILITY_UID', 'arm-vulnerability-risk'),
            'title' => 'Vulnerability & Risk',
            'description' => 'Top CVEs, KEV/EPSS signals, risky assets and observed CPE coverage.',
            'time_range' => 'now-30d',
            'panels' => [
                ['id' => 1, 'title' => 'Active CVE Findings', 'size' => 'stat'],
                ['id' => 2, 'title' => 'Critical CVEs', 'size' => 'stat'],
                ['id' => 3, 'title' => 'KEV Findings', 'size' => 'stat'],
                ['id' => 4, 'title' => 'Average CVSS', 'size' => 'stat'],
                ['id' => 5, 'title' => 'CVE Findings By Severity', 'size' => 'chart'],
                ['id' => 6, 'title' => 'Threat Sources', 'size' => 'chart'],
                ['id' => 9, 'title' => 'Observed CPE Vendors', 'size' => 'chart'],
                ['id' => 10, 'title' => 'Observed CPE Confidence', 'size' => 'chart'],
                ['id' => 7, 'title' => 'Top Observed CVEs', 'size' => 'table'],
                ['id' => 8, 'title' => 'Assets With Highest Risk', 'size' => 'table'],
                ['id' => 11, 'title' => 'Latest Vulnerability Intelligence', 'size' => 'table'],
            ],
        ],
    ],
];
