apiVersion: 1

datasources:
  - name: ARM MariaDB
    uid: arm-mariadb
    type: mysql
    access: proxy
    url: db:3306
    database: ${DB_DATABASE}
    user: ${DB_USERNAME}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true
      maxOpenConns: 20
      maxIdleConns: 20
      connMaxLifetime: 14400
      timeInterval: 1m
      timezone: Europe/Lisbon
